name: Get changed files & folders
on:
  pull_request:
    paths: 
    - 'lambdas/**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        uses: Ana06/get-changed-files@v2.2.0
        id: files
        with:
          format: 'json'
          filter: '*'

      - name: Print files
        run: echo "${{ steps.files.outputs.added_modified_renamed }}"

      - name: Build list of changed folders
        uses: actions/github-script@v6
        id: folders
        env:
          FILES: ${{ steps.files.outputs.added_modified_renamed }}
        with:
          script: |
            const files = JSON.parse(process.env.FILES);
            return files
          result-encoding: string

      - name: Print folders
        run: echo "${{ steps.folders.outputs.result }}"
